const EVENTS_CONSTANTS = Object.freeze({
    EMPLOYEE_REGISTER: "EMPLOYEE_REGISTER",
    ACCOUNT_VERIFICATION: "ACCOUNT_VERIFICATION",
    EMPLOYEE_EVALUATION_SUCCESS: "EMPLOYEE_EVALUATION_SUCCESS",
    EMPLOYEE_EVALUATION_REJECT: "EMPLOYEE_EVALUATION_REJECT",
    EMPLOYEE_END_PROJECT: "EMPLOYEE_END_PROJECT",
    MANAGER_END_PROJECT: "MANAGER_END_PROJECT",
    FORGOT_PASSWORD: "FORGOT_PASSWORD" ,
    APPLY_OPPORTUNITY: "APPLY_OPPORTUNITY" ,
    RECOMMENDED_OPPORTUNITY : 'RECOMMENDED_OPPORTUNITY'
})
module.exports = EVENTS_CONSTANTS;